### PR TITLE
RenameKey funcionality

### PR DESCRIPTION
**Pull request by atomcat1978**
Added renameKey feature to rename a key value found in a map path to a new key value. This gratly increases the usability of the library. Unit tests were also extended to cover the new feature.

### CODE REVIEW

**Comment by atomcat1978** [comment]
Hi,

Is this pull request going to be included? Added a lot of features, and also fixed a pretty bad bug while removing array items using the library.

**Comment by kallestenflo** [comment]
Yes I will include it.

**Comment by ldziedziul** [comment]
Hi. Could you merge this pull request? It will save me (and probably others) a lot of work.

**Comment by atomcat1978** [comment]
@kallestenflo Can You please merge this pull request? Apparently people would like to use the added features and fixes. Also we are closing our project soon, it would be nice to use the official master branch instead of a private forked version.

**Comment by kallestenflo** [comment]
I can't promise a release date. This project is developed on my spare time and I don't have a lot of that at the moment. 

I need to look into your change in AbstractJsonProvider. Is this the bug you mention in previous comment? This will alter the behavior of all Map based JsonProviders.

**Comment by johim** [comment]
+1 for this functionality. I had to use this in one of our latest projects and had to write custom code for this to rename a key.

**Comment by atomcat1978** [comment]
Sure, I know. Just it is on hold for quite a long time ago.

Yes, the AbstractJsonProvider modification is related to commit "Fix for list element removal if multiple path elements match" (48544d1), which was missing a tes file (`json-path/src/test/resources/json_array_multiple_delete.json`), that's why another commit was made (0042ae9).

**Comment by kallestenflo** [comment]
@atomcat1978 I made some modifications to your commit. One thing I did was reverting your change in AbstractJsonProvider.removeProperty(...). You say there is bug in this method, could you provide a test that triggers this?

**Comment by bwaldvogel** [comment]
Thanks. When do you plan to release the next version which contains the rename feature?

**Comment by atomcat1978** [comment]
Hi @kallestenflo ,
I've checked the AbstractJsonProvider.removeProperty affair again. The way how the delete operation in case of arrays is handled has beed updated. Now the operations are sorted based on the array index of the delete operation. This way the functionality works totally ok, there is no need to update the AbstractJsonProvider.removeProperty method any more. Thanks for merging in. Do You have an estimated date for the next release?

**Comment by kallestenflo** [comment]
Perfect! 
I'm trying to fix all issues tagged with BUG. #141 is in progress but it requires a rewrite that is big. I hope to complete it this week and release the week after. This is not a promise.

**Comment by atomcat1978** [comment]
Thanks for the great work in advance!

**Comment by kallestenflo** [comment]
I think I will rename convert(ValueConverter vc) to map(Mapper m). Any thoughts on this? This is the last thing I will do before release. 
Appreciate your contributions and input.

**Comment by atomcat1978** [comment]
You are welcome.

Thanks for the update. I think, Map is and MapFunction are ok, and easy to understand.

I'll try to move over our project to the official latest release:) Thanks for the new release!

**Pull request merged**
