### PR TITLE
use json-smart to parse the query

### PR DESCRIPTION
**Pull request by jochenberger**
As I see it, the JsonProvider is only responsible to read the *data*, not the *query*.
See also #305, #275, but also #274.

### CODE REVIEW

**Comment by jochenberger** [comment]
I guess, `JsonNode' shouldn't use the provider at all.

**Comment by jochenberger** [comment]
This reverts parts of #101

**Comment by kallestenflo** [comment]
Is this the only reason for JsonSmart to be a mandatory dependency?

**Comment by jochenberger** [comment]
IMHO, Using json-smart as the default provider makes it a mandatory dependency, otherwise we ship a broken default config, don't we?

**Comment by jochenberger** [comment]
In the `build.gradle`, the dependency is mandatory already. I must admit though that I don't know anything about the whole OSGi topic.

**Comment by kallestenflo** [comment]
I think it's common to exlude JsonSmart in some scenarios like Android. The main reason for this has been the ASM issues in JsonSmart. That should not be an issue now?

**Comment by jochenberger** [comment]
Yes, that should be dealt with in #334.
But excluding the dependency and marking the classes as optional in the OSGi manifest are two different things. I'm just not away of the effects of the latter.

**Pull request merged**
