### PR TITLE
Implement boolean negation '!' operator for filter expressions

### PR DESCRIPTION
**Pull request by arifogel**
I didn't see a way to negate e.g. the match of a regex, so I implemented full negation of expressions.

### CODE REVIEW

**Comment by hammer2j2** [comment]
Awesome!  This will immediately double the size of the results domain of filter expressions! ;-)
But, seriously, I've been waiting for this a long time.  

Thank you.

**Comment by kallestenflo** [comment]
Looking good! Could you please add some tests that verifies expected behaviour?

**Comment by epacke** [comment]
Any news about this PR? Looking for this functionality and it would save a lot of time!

**Comment by arifogel** [comment]
I believe it is held up because I never submitted tests. Unfortunately I am
extraordinarily busy and this has not been a priority for me. If someone
would like to jump in and add tests then this could likely get merged soon.

**Comment by epacke** [comment]
I see. If I knew how I would do it, but I'm pretty much still in the "Hello world" phase. Hope you'll be less busy soon for your own sake if not for this PR. Thank you for replying! :)

**Comment by arifogel** [comment]
If you need this functionality in the meantime, you can use the release I
put on my fork:
https://github.com/arifogel/JsonPath/releases/tag/2.2.1-SNAPSHOT-arifogel

**Comment by epacke** [comment]
Thank you Ari!

**Comment by epacke** [comment]
Yaye! :)

**Pull request merged**
