### PR TITLE
[#119] First implementation of hamcrest-matchers

### PR DESCRIPTION
**Pull request by helsing**
Initial implementation put in json-path-assert module, as we discussed. Please advice on any improvements that need to be made before we can merge.

Cheers

### CODE REVIEW

**Comment by kallestenflo** [comment]
Looking good! I will pull this as soon as I have released 1.2.1.

**Comment by helsing** [comment]
Ok, sweet :-) Do you mind if I provide a second commit, to reduce the amount of code and also adding a README?

**Comment by kallestenflo** [comment]
Keep it coming!

**Comment by helsing** [comment]
Done. Unless you have some feedback?

**Pull request merged**
