### PR TITLE
Remove slf4j

### PR DESCRIPTION
**Pull request by trajano**
This reduces the [dependency convergence][1] problems with slf4j when using json-path in other projects.

All the logging was removed in commit fe0b46f.  Another approach could be to use the `java.util.logging` which will not cause any [dependency convergence][1] issues.

[1]: https://maven.apache.org/enforcer/enforcer-rules/dependencyConvergence.html

### CODE REVIEW

**Comment by kallestenflo** [comment]
Is this really an issue? I thought slf4j was more or less a standard these days and i don't like JUL. 

By the way It's only 32 KB.

**Comment by trajano** [comment]
It may be 32k but if some other package uses it and happens to have a different version the API may not be compatible and we will also get dependency convergence issues with maven enforcer. 




Same issues with Guava which I had addressed in part of json schema validator. Since json path is meant to be a library it really should avoid adding any transitive dependencies.

**Comment by kallestenflo** [comment]
The only dependencies we have are json-smart and slf4j. json-smart can be excluded in favor of Jackson or GSON, both are optional. I would say that is avoiding transitive dependencies. 

http://www.slf4j.org/codes.html#version_mismatch
>From the client's perspective all versions of slf4j-api are compatible. Client code compiled with slf4j-api-N.jar will run perfectly fine with slf4j-api-M.jar for any N and M. You only need to ensure that the version of your binding matches that of the slf4j-api.jar. You do not have to worry about the version of slf4j-api.jar used by a given dependency in your project. You can always use any version of slf4j-api.jar, and as long as the version of slf4j-api.jar and its binding match, you should be fine.



Any one else that would like to get rid of slf4j and I might reconsider.

**Comment by trajano** [comment]
No problem. The nice part about open source with GitHub is easy forks.  I also generally avoid logging in libraries if possible. In addition I tend to have better control of application server logging with java util logging as the app servers I use glassed fish and web sphere have native hooks for it already and I can adjust the filters. Though I is generally the wrong word. It's generally production and ops people that set the logging. Rules. 




I try to avoid the issue with libraries I build by using the javaee libraries as much as possible. 




The use of jSon smart I have taken out of my fork already. I just chose Jackson for the time being because I was forced to use it on another package. I can't wait till you figure out how to do the json api. That will remove one more dependency

**Comment by trajano** [comment]
Mind you I hate JUL the api. :). I had started to write a code generator to write the JUL code for me with a saner API without any extra runtime libraries. Using another tool I developed called jetng

**Comment by trajano** [comment]
I'll create two separate PRs for the two commits 0f3d143 (a logger which I forgot to remove) and 85ec58a (which introduces a separate constructor for `ValueCompareException` that will take the debug message and put it as a message on the exception itself.

**Comment by kallestenflo** [comment]
I will close this for now but I have noted your request to drop slf4j.

**Pull request closed without merging**
