### PR TITLE
Use jcache

### LINKED ISSUE #94: memory leak
One of our QA servers ran out of memory, looks like there is a memory leak in Cache.java.
A simple single-threaded program to reproduce the issue is below.
I think it is better to allow the user to disable the cache, and let the user create (and cache) CompiledPath instances.

    public static void main(String[] arg) {
        Cache cache = new Cache(200);
        Path dummy = new CompiledPath(null, false);
        for (int i = 0; i < 10000; ++i) {
           String key = String.valueOf(i);
           cache.get(key);
           cache.put(key, dummy);
        }
        System.out.println("cache size: " + cache.size());
    }

### PR DESCRIPTION
**Pull request by trajano**
Fixes #94 

I also removed an unused logger and applied the IntelliJ suggestion for Gradle.

I also changed to use the new Travis infrastructure to save on the build time.  Seems to reduce by ~20 seconds

### CODE REVIEW

**Comment by kallestenflo** [comment]
@trajano was it not you who argued for the removal of `slf4j-api` to reduce external dependencies?
I don't want to add new dependencies. If we provide a simple SPI, something like #137, it will be a breeze to plug in JSR-107.

**Comment by trajano** [comment]
Correct. However It actually won't add any dependency as soon as Java EE 8 comes out. This allows for future proofing and allows for use of any JSR107 compatible SPIs such as Google App Engine. Hazel cast. EhCache.




The problem with providing a cache SPI is that it is duplicating the effort of an established standard in Java EE. At least when it comes out. 




Slf4j is not part of any standard in comparison.

**Comment by kallestenflo** [comment]
I see your point but not all users are running Java EE. I think one of the reasons that so many project  use this implementation is because of the relatively small footprint. There are even Android projects on the list...

**Comment by trajano** [comment]
I see your point.  However, rather than using a "cache" have you considered
just using a simple map?  Does the map really grow that big that we need to
limit the capacity and deal with concurrency issues?

On Wed, Oct 14, 2015 at 3:16 PM, kallestenflo <notifications@github.com>
wrote:

> I see your point but not all users are running Java EE. I think one of the
> reasons that so many project use this implementation is because of the
> relatively small footprint. There are even Android projects on the list...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jayway/JsonPath/pull/138#issuecomment-148164119>.
>



-- 
Archimedes Trajano
www.trajano.net

**Comment by kallestenflo** [comment]
Closing this in favor of #137 that makes it possible to plug in JCache if you are in an Java EE context. The SPI should come with:

* Simple Cache (Map)
* LRU Cache
* NOOP Cache

**Pull request closed without merging**
